from __future__ import annotations

import datetime as dt
import re
from pathlib import Path
from typing import Literal
from zoneinfo import ZoneInfo

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
from ruamel.yaml.error import YAMLError

from .tokens import TOKEN_RE, derive_id, mint_token

yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 100


class ConfigError(ValueError):
    pass


LINKS_FILENAME = ".links.yaml"
LINKS_HEADER = "Machine-generated by `partyplanner link`; do not edit by hand. Commit this file."


class Landing(BaseModel):
    model_config = ConfigDict(extra="forbid")

    blurb: str | None = None
    photo: str | None = None
    embed: str | None = None  # path to an HTML fragment injected into the landing page


EVENT_ID_RE = re.compile(r"^[a-z0-9-]{1,64}\Z")
COLOR_RE = re.compile(r"^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\Z")


def _check_color(v: str | None) -> str | None:
    if v is not None and not COLOR_RE.match(v):
        raise ValueError(f"color {v!r} must be a hex color like #7a3ff2")
    return v


class Theme(BaseModel):
    model_config = ConfigDict(extra="forbid")

    accent: str | None = None
    bg: str | None = None
    ink: str | None = None
    muted: str | None = None
    card: str | None = None

    _colors = field_validator("accent", "bg", "ink", "muted", "card")(_check_color)


class Event(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str | None = None
    title: str
    when: dt.datetime | None = None
    end: dt.datetime | None = None
    where: str | None = None
    where_url: str | None = None
    blurb: str | None = None
    photo: str | None = None
    accent: str | None = None
    rsvp: Literal["open", "none"] = "open"

    _accent = field_validator("accent")(_check_color)

    @field_validator("id")
    @classmethod
    def _check_id(cls, v: str | None) -> str | None:
        if v is not None and not EVENT_ID_RE.match(v):
            raise ValueError(f"event id {v!r} must match [a-z0-9-] and be at most 64 chars")
        return v

    @field_validator("when", "end", mode="before")
    @classmethod
    def _parse_datetime(cls, v: object) -> object:
        if isinstance(v, str):
            return dt.datetime.fromisoformat(v)
        if isinstance(v, dt.date) and not isinstance(v, dt.datetime):
            return dt.datetime(v.year, v.month, v.day)
        return v

    @field_validator("where_url")
    @classmethod
    def _check_where_url(cls, v: str | None) -> str | None:
        if v is not None and not v.startswith(("https://", "http://")):
            raise ValueError(f"where_url {v!r} must be an http(s) URL")
        return v

    @model_validator(mode="after")
    def _check(self) -> Event:
        if self.where_url is not None and self.where is None:
            raise ValueError(f"event {self.title!r} has a `where_url` but no `where`")
        if self.rsvp == "open" and self.when is None:
            raise ValueError(f"event {self.title!r} has rsvp: open and needs a `when`")
        if self.end is not None and self.when is None:
            raise ValueError(f"event {self.title!r} has an `end` but no `when`")
        if self.end is not None and self.when is not None:
            if (self.end.tzinfo is None) != (self.when.tzinfo is None):
                raise ValueError(
                    f"event {self.title!r} mixes offset-aware and naive times for when/end"
                )
            if self.end <= self.when:
                raise ValueError(f"event {self.title!r} ends before it starts")
        return self


class Link(BaseModel):
    model_config = ConfigDict(extra="forbid")

    token: str | None = None
    scope: str | list[str] = "all"
    prefill_name: str | None = None
    note: str | None = None

    @field_validator("token")
    @classmethod
    def _check_token(cls, v: str | None) -> str | None:
        if v is not None and not TOKEN_RE.match(v):
            raise ValueError(f"token {v!r} is not lowercase base32 of 16-64 chars")
        return v

    @field_validator("prefill_name")
    @classmethod
    def _check_prefill(cls, v: str | None) -> str | None:
        if v is None:
            return v
        v = " ".join(v.split())  # same normalization the RSVP API applies to names
        if not 1 <= len(v) <= 40 or not v.isprintable():
            raise ValueError(f"prefill_name {v!r} must be 1-40 printable characters")
        return v


class Occasion(BaseModel):
    model_config = ConfigDict(extra="forbid")

    title: str
    domain: str
    timezone: str
    photo: str | None = None
    favicon: str | None = None
    blurb: str | None = None
    theme: Theme | None = None
    landing: Landing | None = None
    events: list[Event] = Field(min_length=1)
    scopes: dict[str, list[str]] = Field(default_factory=dict)
    links: list[Link] = Field(default_factory=list)
    revoked: list[str] = Field(default_factory=list)
    admin_key: str | None = None

    @field_validator("admin_key")
    @classmethod
    def _check_admin_key(cls, v: str | None) -> str | None:
        if v is not None and not TOKEN_RE.match(v):
            raise ValueError(f"admin_key {v!r} is not lowercase base32 of 16-64 chars")
        return v

    @field_validator("domain")
    @classmethod
    def _check_domain(cls, v: str) -> str:
        if len(v) > 253 or not re.match(
            r"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}\Z", v
        ):
            raise ValueError(f"domain {v!r} is not a valid lowercase hostname")
        return v

    @field_validator("revoked")
    @classmethod
    def _check_revoked(cls, v: list[str]) -> list[str]:
        for t in v:
            if not TOKEN_RE.match(t):
                raise ValueError(f"revoked token {t!r} is not lowercase base32 of 16-64 chars")
        dupes = {t for t in v if v.count(t) > 1}
        if dupes:
            raise ValueError(f"duplicate revoked tokens: {sorted(dupes)}")
        return v

    @field_validator("timezone")
    @classmethod
    def _check_timezone(cls, v: str) -> str:
        try:
            ZoneInfo(v)
        except Exception as e:
            raise ValueError(f"unknown timezone {v!r}") from e
        return v

    @model_validator(mode="after")
    def _check(self) -> Occasion:
        ids = [e.id for e in self.events if e.id is not None]
        dupes = {i for i in ids if ids.count(i) > 1}
        if dupes:
            raise ValueError(f"duplicate event ids: {sorted(dupes)}")
        if any(e.id is None for e in self.events):
            titles = [e.title for e in self.events]
            if len(set(titles)) != len(titles):
                raise ValueError("event titles must be unique when ids are omitted")
            derived = [e.id or derive_id(e.title) for e in self.events]
            if len(set(derived)) != len(derived):
                raise ValueError(f"derived event ids collide: {derived}; set explicit ids")
        known = {e.id or derive_id(e.title) for e in self.events}
        for name, members in self.scopes.items():
            unknown = set(members) - known
            if unknown:
                raise ValueError(f"scope {name!r} references unknown events: {sorted(unknown)}")
        for link in self.links:
            self.resolve_scope(link)
            if link.token is not None and link.token in self.revoked:
                raise ValueError(
                    f"link token {link.token!r} is listed in `revoked:`; delete the token "
                    "from the link entry so a replacement is minted"
                )
        tokens = [link.token for link in self.links if link.token is not None]
        if len(set(tokens)) != len(tokens):
            raise ValueError("duplicate link tokens")
        if self.admin_key is not None and self.admin_key in tokens:
            raise ValueError("admin_key collides with a link token")
        return self

    @property
    def tz(self) -> ZoneInfo:
        return ZoneInfo(self.timezone)

    def event_ids(self) -> list[str]:
        return [e.id or derive_id(e.title) for e in self.events]

    def resolve_scope(self, link: Link) -> tuple[str, ...]:
        """Resolve a link's scope to an ordered tuple of event ids (config order)."""
        order = self.event_ids()
        if link.scope == "all":
            return tuple(order)
        if isinstance(link.scope, str):
            if link.scope not in self.scopes:
                raise ValueError(f"link references unknown scope preset {link.scope!r}")
            members = set(self.scopes[link.scope])
        else:
            unknown = set(link.scope) - set(order)
            if unknown:
                raise ValueError(f"link scope references unknown events: {sorted(unknown)}")
            members = set(link.scope)
        return tuple(i for i in order if i in members)

    def rsvp_open_ids(self) -> set[str]:
        return {e.id or derive_id(e.title) for e in self.events if e.rsvp == "open"}

    def latest_end(self) -> dt.datetime | None:
        """Latest event end (or start) as an aware datetime, for data TTL."""
        stamps = []
        for e in self.events:
            t = e.end or e.when
            if t is not None:
                stamps.append(t if t.tzinfo else t.replace(tzinfo=self.tz))
        return max(stamps) if stamps else None


def load_raw(path: Path) -> CommentedMap:
    try:
        with path.open() as f:
            data = yaml.load(f)
    except YAMLError as e:
        raise ConfigError(f"{path}: invalid YAML: {e}") from e
    if not isinstance(data, CommentedMap):
        raise ConfigError(f"{path}: expected a YAML mapping at the top level")
    return data


def parse(data: CommentedMap, path: Path | None = None) -> Occasion:
    try:
        return Occasion.model_validate(data)
    except ValueError as e:
        prefix = f"{path}: " if path else ""
        raise ConfigError(f"{prefix}{e}") from e


def _load_links_raw(path: Path) -> CommentedMap:
    data = load_raw(path)
    unknown = set(data.keys()) - {"links", "revoked", "admin_key"}
    if unknown:
        raise ConfigError(
            f"{path}: unexpected keys {sorted(unknown)}; only links/revoked/admin_key allowed"
        )
    return data


def merged_raw(path: Path) -> CommentedMap:
    """The occasion config with links/revoked from the sibling links file merged in."""
    data = load_raw(path)
    links_path = path.parent / LINKS_FILENAME
    if links_path.exists():
        extra = _load_links_raw(links_path)
        for key in ("links", "revoked"):
            if extra.get(key):
                data[key] = list(data.get(key) or []) + list(extra[key])
        if extra.get("admin_key") and not data.get("admin_key"):
            data["admin_key"] = extra["admin_key"]
    return data


def load(path: Path) -> Occasion:
    return parse(merged_raw(path), path)


def add_link(
    config_path: Path,
    scope: str | list[str],
    note: str | None = None,
    prefill_name: str | None = None,
) -> Link:
    """Mint a new link into the links file next to the config. Returns the link."""
    if isinstance(scope, list) and not scope:
        raise ConfigError("scope must not be empty")
    occasion = load(config_path)
    try:
        link = Link(token=mint_token(), scope=scope, prefill_name=prefill_name, note=note)
        occasion.resolve_scope(link)
    except ValueError as e:
        raise ConfigError(str(e)) from e

    links_path = config_path.parent / LINKS_FILENAME
    data = _load_links_raw(links_path) if links_path.exists() else CommentedMap()
    if not links_path.exists():
        data.yaml_set_start_comment(LINKS_HEADER)
    entry = CommentedMap()
    entry["token"] = link.token
    entry["scope"] = link.scope
    if link.prefill_name:
        entry["prefill_name"] = link.prefill_name
    if link.note:
        entry["note"] = link.note
    if not data.get("links"):
        data["links"] = CommentedSeq()
    data["links"].append(entry)
    original = links_path.read_text() if links_path.exists() else None
    with links_path.open("w") as f:
        yaml.dump(data, f)
    try:
        load(config_path)  # re-validate the merged result
    except ConfigError:
        if original is None:
            links_path.unlink()
        else:
            links_path.write_text(original)
        raise
    return link


def ensure_admin_key(config_path: Path) -> tuple[str, bool]:
    """The occasion's admin key, minting one into the links file if absent.

    Returns (key, minted): `minted` is True when a new key was written.
    """
    occasion = load(config_path)
    if occasion.admin_key is not None:
        return occasion.admin_key, False
    links_path = config_path.parent / LINKS_FILENAME
    data = _load_links_raw(links_path) if links_path.exists() else CommentedMap()
    if not links_path.exists():
        data.yaml_set_start_comment(LINKS_HEADER)
    key = mint_token()
    data["admin_key"] = key
    original = links_path.read_text() if links_path.exists() else None
    with links_path.open("w") as f:
        yaml.dump(data, f)
    try:
        load(config_path)  # re-validate the merged result
    except ConfigError:
        if original is None:
            links_path.unlink()
        else:
            links_path.write_text(original)
        raise
    return key, True


def revoke_link(config_path: Path, token: str) -> None:
    """Move a generated link's token to `revoked:` in the links file."""
    links_path = config_path.parent / LINKS_FILENAME
    data = _load_links_raw(links_path) if links_path.exists() else CommentedMap()
    links = data.get("links") or []
    matches = [
        i
        for i, node in enumerate(links)
        if isinstance(node, CommentedMap) and node.get("token") == token
    ]
    index = matches[0] if matches else None
    if index is None:
        occasion = load(config_path)
        if any(link.token == token for link in occasion.links):
            raise ConfigError(
                f"token {token!r} lives in {config_path}; delete its entry there and add the "
                f"token under `revoked:` by hand"
            )
        raise ConfigError(f"unknown token {token!r}")
    del links[index]
    if not data.get("revoked"):
        data["revoked"] = CommentedSeq()
    data["revoked"].append(token)
    original = links_path.read_text()
    with links_path.open("w") as f:
        yaml.dump(data, f)
    try:
        load(config_path)  # re-validate the merged result
    except ConfigError:
        links_path.write_text(original)
        raise


def mint(path: Path) -> list[str]:
    """Fill in missing event ids and link tokens, writing back to the config file.

    Preserves comments and formatting. Returns human-readable notes of what changed.
    """
    data = load_raw(path)
    occasion = parse(merged_raw(path), path)  # validate the merged view before mutating
    notes: list[str] = []

    events = data.get("events")
    if isinstance(events, CommentedSeq):
        for node, event in zip(events, occasion.events, strict=True):
            if isinstance(node, CommentedMap) and node.get("id") is None:
                new_id = derive_id(event.title)
                node.pop("id", None)  # a bare `id:` parses as null; replace it
                node.insert(0, "id", new_id)
                notes.append(f"event {event.title!r}: id = {new_id}")

    links = data.get("links")
    if isinstance(links, CommentedSeq):
        for i, node in enumerate(links):
            if isinstance(node, CommentedMap) and node.get("token") is None:
                token = mint_token()
                node.pop("token", None)  # a bare `token:` parses as null; replace it
                node.insert(0, "token", token)
                label = node.get("prefill_name") or node.get("note") or f"link #{i + 1}"
                notes.append(f"link {label!r}: token = {token}")

    if notes:
        with path.open("w") as f:
            yaml.dump(data, f)
        parse(merged_raw(path), path)  # re-validate what we wrote
    return notes


def require_complete(occasion: Occasion, path: Path | None = None) -> None:
    """Fail unless every event has an id and every link a token (i.e. `mint` was run)."""
    missing: list[str] = []
    missing += [f"event {e.title!r} has no id" for e in occasion.events if e.id is None]
    missing += [
        f"link {(link.prefill_name or link.note or f'#{i + 1}')!r} has no token"
        for i, link in enumerate(occasion.links)
        if link.token is None
    ]
    if missing:
        prefix = f"{path}: " if path else ""
        raise ConfigError(
            prefix
            + "; ".join(missing)
            + " — run `partyplanner mint` and commit the result before rendering"
        )
    if not occasion.links:
        raise ConfigError("no links defined; create one with `partyplanner link add`")
